### ISSUE TITLE
Update Emigrants homepage

### ISSUE THREAD

**Issue by wlla** [zooniverse/scribeAPI#475] opened 2015-10-23 19:40 UTC
Implement the design changes from week of 10/5 (made for local screenshots.)

**Comment by beefoo** [comment] 2015-10-29 15:22
* New Logo added w/ Lionmark
* "New York Public Library presents" added before title

Anything else needed?

**Comment by beefoo** [comment] 2015-10-29 15:24
Duplicate of #438 .  Closing

**Closed by beefoo** 2015-10-29 15:24 UTC
Labels: Emigrants
